spring.application.name=function-procedure
server.port=9876

spring.jpa.hibernate.ddl-auto=update
spring.datasource.password=root
spring.datasource.username=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/function_procedure